ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "templateId" TEXT NOT NULL DEFAULT 'classic';
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "designSerif" BOOLEAN NOT NULL DEFAULT true;
ALTER TABLE "Property" ADD COLUMN IF NOT EXISTS "designRounded" BOOLEAN NOT NULL DEFAULT true;
