/**
 * Reports (and optionally deletes) the automated signups that accumulated before
 * signup abuse controls existed.
 *
 *   npx tsx prisma/purge-bot-accounts.ts          # dry run, prints what matches
 *   npx tsx prisma/purge-bot-accounts.ts --delete # actually removes them
 *
 * An account is only considered a bot when it has a machine-generated display
 * name AND owns no property AND has never paid. Requiring all three keeps a real
 * owner with an odd name from being deleted.
 */
import { PrismaClient } from "@prisma/client";
import { canonicalEmail, looksAutoGenerated } from "../lib/email-identity";

const prisma = new PrismaClient();
const shouldDelete = process.argv.includes("--delete");

async function main() {
  const users = await prisma.user.findMany({
    where: { role: "OWNER" },
    select: {
      id: true,
      name: true,
      email: true,
      createdAt: true,
      paddleSubscriptionId: true,
      paddleTransactionId: true,
      paypalSubscriptionId: true,
      _count: { select: { properties: true } }
    }
  });

  const seen = new Map<string, string>();
  const suspects = users.filter((user) => {
    const hasPaid = Boolean(user.paddleSubscriptionId || user.paddleTransactionId || user.paypalSubscriptionId);
    if (hasPaid || user._count.properties > 0) return false;

    if (looksAutoGenerated(user.name)) return true;

    // Second signal: several accounts collapsing to one real inbox.
    const key = canonicalEmail(user.email);
    const first = seen.get(key);
    seen.set(key, user.id);
    return Boolean(first);
  });

  console.log(`${users.length} owner accounts, ${suspects.length} match the bot pattern:`);
  for (const user of suspects) {
    console.log(`  ${user.createdAt.toISOString().slice(0, 10)}  ${user.name.slice(0, 28).padEnd(28)}  ${user.email}`);
  }

  if (!shouldDelete) {
    console.log("\nDry run. Re-run with --delete to remove these accounts.");
    return;
  }

  const { count } = await prisma.user.deleteMany({ where: { id: { in: suspects.map((user) => user.id) } } });
  console.log(`\nDeleted ${count} accounts (sessions and tokens cascade).`);
}

main()
  .catch((error) => {
    console.error(error);
    process.exitCode = 1;
  })
  .finally(() => prisma.$disconnect());
