"use server";

import { randomBytes } from "node:crypto";
import { headers } from "next/headers";
import { redirect } from "next/navigation";
import { prisma } from "@/lib/prisma";
import { verifyCaptcha } from "@/lib/captcha";
import { canonicalEmail, isDisposableEmail, isValidEmailShape, looksAutoGenerated } from "@/lib/email-identity";
import { rateLimit } from "@/lib/rate-limit";
import { sendVerificationEmail } from "@/lib/verification";
import { createSession, destroyAllUserSessions, destroyOtherSessions, destroySession, hashToken, requireCurrentUser } from "@/lib/auth";
import { sendEmail } from "@/lib/email";
import { hashPassword, verifyPassword } from "@/lib/password";
import { passwordRulesText, validatePassword } from "@/lib/password-policy";
import { normalizePlanKey, startTrial } from "@/lib/billing";
import { getAppUrl } from "@/lib/utils";
import { claimPropertyPreview } from "@/lib/property-preview";

function stringValue(formData: FormData, key: string) {
  const value = formData.get(key);
  return typeof value === "string" ? value.trim() : "";
}

function normalizeEmail(email: string) {
  return email.toLowerCase().trim();
}

/** Client IP inside a server action, where there is no Request object. */
function headerClientIp() {
  const store = headers();
  const forwarded = store.get("x-forwarded-for");
  if (forwarded) return forwarded.split(",")[0]!.trim();
  return store.get("x-real-ip")?.trim() || "unknown";
}

function redirectWithError(path: string, message: string): never {
  const separator = path.includes("?") ? "&" : "?";
  redirect(`${path}${separator}error=${encodeURIComponent(message)}`);
}

function safeRedirectTarget(value: string) {
  if (!value.startsWith("/") || value.startsWith("//") || value.includes("\\")) return "/dashboard";
  return value;
}

export async function registerOwner(formData: FormData) {
  const name = stringValue(formData, "name");
  const email = normalizeEmail(stringValue(formData, "email"));
  const password = stringValue(formData, "password");
  const confirmPassword = stringValue(formData, "confirmPassword");
  const planKey = normalizePlanKey(stringValue(formData, "plan"));
  const previewToken = stringValue(formData, "previewToken");
  
  const queryParams = new URLSearchParams({ plan: planKey });
  if (previewToken) queryParams.set("previewToken", previewToken);
  
  const registerPath = `/register?${queryParams.toString()}`;

  if (!name || !email || !password) {
    redirectWithError(registerPath, "Please complete every required field.");
  }

  if (password !== confirmPassword) {
    redirectWithError(registerPath, "Passwords do not match.");
  }

  const passwordErrors = validatePassword(password);
  if (passwordErrors.length > 0) {
    redirectWithError(registerPath, `Password must include ${passwordErrors.join(", ")}.`);
  }

  // Signup abuse controls. Ordered cheapest-first so obvious junk never reaches
  // the database or Cloudflare.
  if (!isValidEmailShape(email)) {
    redirectWithError(registerPath, "Please enter a valid email address.");
  }

  if (isDisposableEmail(email)) {
    redirectWithError(registerPath, "Please sign up with a permanent email address.");
  }

  if (looksAutoGenerated(name)) {
    redirectWithError(registerPath, "Please enter your real name.");
  }

  const ip = headerClientIp();
  const ipLimit = await rateLimit(`register:ip:${ip}`, 5, 60 * 60);
  if (!ipLimit.allowed) {
    redirectWithError(registerPath, "Too many sign-up attempts. Please try again later.");
  }

  if (!(await verifyCaptcha(stringValue(formData, "cf-turnstile-response"), ip))) {
    redirectWithError(registerPath, "Could not verify you are human. Please try again.");
  }

  const emailCanonical = canonicalEmail(email);
  const existingUser = await prisma.user.findFirst({
    where: { OR: [{ email }, { emailCanonical }] },
    select: { id: true }
  });
  if (existingUser) {
    redirectWithError(registerPath, "An account with this email already exists. Please log in.");
  }

  const user = await prisma.user.create({
    data: {
      name,
      email,
      emailCanonical,
      passwordHash: hashPassword(password),
      selectedPlan: planKey,
      ...startTrial()
    }
  });

  // Sent but not enforced as a gate: the owner can build their guide right away,
  // while an unconfirmed address still blocks the guide from going public.
  await sendVerificationEmail(user).catch(() => undefined);

  await createSession(user.id);
  
  if (previewToken) {
    const claimedProperty = await claimPropertyPreview(previewToken, user.id);
    if (claimedProperty) {
      redirect("/dashboard?preview=claimed");
    }
  }

  // Owners land in the product on their trial. Billing is prompted from the
  // dashboard as the trial runs down, not as a wall in front of the first visit.
  redirect("/dashboard?welcome=1");
}

export async function loginOwner(formData: FormData) {
  const email = normalizeEmail(stringValue(formData, "email"));
  const password = stringValue(formData, "password");
  const next = stringValue(formData, "next") || "/dashboard";
  const loginPath = `/login?next=${encodeURIComponent(next)}`;

  // Throttle per-IP and per-account so neither password spraying nor a targeted
  // brute force gets unlimited attempts.
  const ip = headerClientIp();
  const [ipLimit, accountLimit] = await Promise.all([
    rateLimit(`login:ip:${ip}`, 20, 15 * 60),
    rateLimit(`login:email:${canonicalEmail(email)}`, 10, 15 * 60)
  ]);
  if (!ipLimit.allowed || !accountLimit.allowed) {
    redirectWithError(loginPath, "Too many sign-in attempts. Please wait a few minutes and try again.");
  }

  const user = await prisma.user.findUnique({ where: { email } });
  if (!user || !user.passwordHash || !verifyPassword(password, user.passwordHash)) {
    redirectWithError(loginPath, "Invalid email or password.");
  }

  await createSession(user.id);

  if (user.mustChangePassword) {
    redirect("/change-password");
  }

  redirect(safeRedirectTarget(next));
}

export async function changePassword(formData: FormData) {
  const user = await requireCurrentUser();
  const currentPassword = stringValue(formData, "currentPassword");
  const newPassword = stringValue(formData, "newPassword");
  const confirmPassword = stringValue(formData, "confirmPassword");

  if (!user.passwordHash || !verifyPassword(currentPassword, user.passwordHash)) {
    redirectWithError("/change-password", "Current password is incorrect.");
  }

  if (newPassword !== confirmPassword) {
    redirectWithError("/change-password", "New passwords do not match.");
  }

  const passwordErrors = validatePassword(newPassword);
  if (passwordErrors.length > 0) {
    redirectWithError("/change-password", `Password must include ${passwordErrors.join(", ")}.`);
  }

  await prisma.user.update({
    where: { id: user.id },
    data: {
      passwordHash: hashPassword(newPassword),
      mustChangePassword: false
    }
  });

  await destroyOtherSessions(user.id);

  redirect("/dashboard");
}

export async function logoutOwner() {
  await destroySession();
  redirect("/login");
}

export async function requestPasswordReset(formData: FormData) {
  const email = normalizeEmail(stringValue(formData, "email"));

  // Reset mail is an outbound send triggered by an anonymous request, so it is
  // capped hard. The response is identical either way to avoid leaking which
  // addresses exist.
  const ip = headerClientIp();
  const [ipLimit, accountLimit] = await Promise.all([
    rateLimit(`reset:ip:${ip}`, 5, 60 * 60),
    rateLimit(`reset:email:${canonicalEmail(email)}`, 3, 60 * 60)
  ]);

  const user = ipLimit.allowed && accountLimit.allowed ? await prisma.user.findUnique({ where: { email } }) : null;

  if (user) {
    await prisma.passwordResetToken.deleteMany({ where: { userId: user.id } });

    const token = randomBytes(32).toString("base64url");
    const expiresAt = new Date(Date.now() + 60 * 60 * 1000);

    await prisma.passwordResetToken.create({
      data: {
        userId: user.id,
        tokenHash: hashToken(token),
        expiresAt
      }
    });

    const resetUrl = `${getAppUrl()}/reset-password?token=${token}`;
    await sendEmail({
      to: user.email,
      subject: "Reset your StayNest password",
      text: `Reset your StayNest password here:\n${resetUrl}\n\nThis link expires in 1 hour.\n\n${passwordRulesText()}`,
      html: `
        <div style="font-family:Inter,Arial,sans-serif;line-height:1.6;color:#1f2933">
          <h1 style="font-size:24px">Reset your StayNest password</h1>
          <p>Use the link below to set a new password. It expires in 1 hour.</p>
          <p><a href="${resetUrl}" style="display:inline-block;background:#1f2933;color:white;padding:12px 18px;border-radius:999px;text-decoration:none;font-weight:700">Reset password</a></p>
          <p style="color:#6b7280;font-size:14px">${passwordRulesText()}</p>
        </div>
      `
    });
  }

  redirect(`/forgot-password?sent=1&email=${encodeURIComponent(email)}`);
}

export async function resetPassword(formData: FormData) {
  const token = stringValue(formData, "token");
  const newPassword = stringValue(formData, "newPassword");
  const confirmPassword = stringValue(formData, "confirmPassword");

  if (newPassword !== confirmPassword) {
    redirectWithError(`/reset-password?token=${encodeURIComponent(token)}`, "Passwords do not match.");
  }

  const passwordErrors = validatePassword(newPassword);
  if (passwordErrors.length > 0) {
    redirectWithError(`/reset-password?token=${encodeURIComponent(token)}`, `Password must include ${passwordErrors.join(", ")}.`);
  }

  const resetToken = await prisma.passwordResetToken.findFirst({
    where: {
      tokenHash: hashToken(token),
      expiresAt: { gt: new Date() }
    }
  });

  if (!resetToken) {
    redirectWithError("/forgot-password", "Reset link is invalid or expired.");
  }

  await prisma.user.update({
    where: { id: resetToken.userId },
    data: {
      passwordHash: hashPassword(newPassword),
      mustChangePassword: false
    }
  });

  await destroyAllUserSessions(resetToken.userId);
  await prisma.passwordResetToken.deleteMany({ where: { userId: resetToken.userId } });
  redirect("/login?reset=1");
}
