/**
 * Email canonicalisation and abuse checks for signup.
 *
 * The bot signups this app collected all used one trick: Gmail treats
 * `u.s.e.r@gmail.com`, `user+tag@gmail.com` and `user@googlemail.com` as the same
 * inbox, but a naive unique-on-email constraint sees each variant as a new person.
 * Canonicalising before the uniqueness check collapses them back into one account.
 */

const gmailDomains = new Set(["gmail.com", "googlemail.com"]);

/** Providers where `+tag` is an alias of the base address. */
const plusAliasDomains = new Set([
  "gmail.com",
  "googlemail.com",
  "outlook.com",
  "hotmail.com",
  "live.com",
  "fastmail.com",
  "protonmail.com",
  "proton.me",
  "icloud.com",
  "me.com"
]);

const disposableDomains = new Set([
  "mailinator.com",
  "guerrillamail.com",
  "10minutemail.com",
  "tempmail.com",
  "temp-mail.org",
  "throwawaymail.com",
  "yopmail.com",
  "trashmail.com",
  "sharklasers.com",
  "getnada.com",
  "dispostable.com",
  "maildrop.cc",
  "mintemail.com",
  "fakeinbox.com",
  "tempr.email",
  "moakt.com",
  "emailondeck.com",
  "mohmal.com",
  "spamgourmet.com",
  "mailnesia.com"
]);

export function splitEmail(email: string) {
  const trimmed = email.trim().toLowerCase();
  const at = trimmed.lastIndexOf("@");
  if (at <= 0 || at === trimmed.length - 1) return null;
  return { local: trimmed.slice(0, at), domain: trimmed.slice(at + 1) };
}

/**
 * Returns the deduplication key for an address: the same inbox always maps to the
 * same string. Store this alongside the address the user actually typed.
 */
export function canonicalEmail(email: string) {
  const parts = splitEmail(email);
  if (!parts) return email.trim().toLowerCase();

  let { local } = parts;
  const { domain } = parts;

  if (plusAliasDomains.has(domain)) {
    local = local.split("+")[0]!;
  }

  if (gmailDomains.has(domain)) {
    local = local.replace(/\./g, "");
    return `${local}@gmail.com`;
  }

  return `${local}@${domain}`;
}

export function isDisposableEmail(email: string) {
  const parts = splitEmail(email);
  return parts ? disposableDomains.has(parts.domain) : false;
}

export function isValidEmailShape(email: string) {
  const parts = splitEmail(email);
  if (!parts) return false;
  if (!/^[a-z0-9._%+-]+$/.test(parts.local)) return false;
  if (!/^[a-z0-9.-]+\.[a-z]{2,}$/.test(parts.domain)) return false;
  return true;
}

/**
 * Heuristic for machine-generated display names. The bot signups used random
 * high-entropy strings ("vaMNGtkcHEbSBTbiuMTk") with no separators and mixed case
 * throughout, which real names essentially never look like.
 */
export function looksAutoGenerated(name: string) {
  const value = name.trim();
  if (value.length < 12) return false;
  if (/[\s'’-]/.test(value)) return false;
  if (!/[a-z]/.test(value) || !/[A-Z]/.test(value)) return false;

  // Count case alternations: random strings flip case far more often than names.
  let flips = 0;
  for (let i = 1; i < value.length; i += 1) {
    const prevUpper = value[i - 1] !== value[i - 1]!.toLowerCase();
    const currUpper = value[i] !== value[i]!.toLowerCase();
    if (prevUpper !== currUpper) flips += 1;
  }

  if (flips >= Math.floor(value.length / 3)) return true;

  // Second signal for strings that happen to cluster their capitals: a single
  // real name token is rarely more than a third uppercase ("McDonald" is 25%,
  // "JeanPierre" 20%), whereas random output sits far above that.
  const uppercase = value.replace(/[^A-Z]/g, "").length;
  return uppercase >= 4 && uppercase / value.length >= 0.35;
}
